version: 2.1

jobs:
  trigger-pipeline-job:
    docker:
      - image: cimg/base:current
    parameters:
      pipeline-definition-id:
        type: string
    steps:
      - run: 
          name: Trigger new Pipeline
          command: |
              curl -X POST https://circleci.com/api/v2/project/<project-slug>/pipeline/run \
                   --header "Circle-Token: $CIRCLE_TOKEN" \
                   --header "content-type: application/json" \
                   --data '{"definition_id": "<<parameters.pipeline-defintion-id>>", "config": {"branch": "<your-branch-name>"},"checkout": {"branch": "<your-branch-name>"}"parameters": {"<param-name>": "<param-value>"}}'
